// <auto-generated />
using ForgingAhead.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ForgingAhead.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190521095403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForgingAhead.Models.Character", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dexterity");

                    b.Property<int>("Intelligence");

                    b.Property<bool>("IsActive");

                    b.Property<int>("Level");

                    b.Property<string>("QuestName");

                    b.Property<int>("Strength");

                    b.HasKey("Name");

                    b.HasIndex("QuestName");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ForgingAhead.Models.Equipment", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Attack");

                    b.Property<string>("CharacterName");

                    b.Property<int>("Defense");

                    b.HasKey("Name");

                    b.HasIndex("CharacterName");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ForgingAhead.Models.Quest", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.HasKey("Name");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("ForgingAhead.Models.Character", b =>
                {
                    b.HasOne("ForgingAhead.Models.Quest")
                        .WithMany("Characters")
                        .HasForeignKey("QuestName");
                });

            modelBuilder.Entity("ForgingAhead.Models.Equipment", b =>
                {
                    b.HasOne("ForgingAhead.Models.Character")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterName");
                });
#pragma warning restore 612, 618
        }
    }
}
